### ISSUE TITLE
No support for OCaml ??

### ISSUE THREAD

**Issue by astro-gad** [jubnzv/virtual-types.nvim#14]
I don't know if the project is dead but it seems like even though I added all the prerequisites to my config, the plugin doesn't seem to work in OCaml at all. I used lazygit with lspconfig and added the following lines:

```lua
lsp.ocamllsp.setup{
		capabilities = cmp_capabilities,
		on_attach = require('virtualtypes').on_attach,
		root_dir = lsp.util.root_pattern("*.opam", "esy.json", "package.json", ".git", "dune-project", "dune-workspace", ".spm-project")
}
```

**Comment by jubnzv** [comment]
It works perfectly with [`ocaml-lsp-server`](https://opam.ocaml.org/packages/ocaml-lsp-server/) and Neovim 0.10.0.
