### ISSUE TITLE
proposal, use `vim.api.nvim_buf_set_extmark`

### ISSUE THREAD

**Issue by aspeddro** [jubnzv/virtual-types.nvim#4]
Hi @jubnzv, apparently `nvim_buf_set_virtual_text` should be deprecated for next API revision.

References:
https://github.com/neovim/neovim/pull/15184
https://jdhao.github.io/2021/09/09/nvim_use_virtual_text

**Comment by jubnzv** [comment]
Hi @aspeddro,
Thank you for the information! This plugin will now use `vim.api.nvim_buf_set_extmark` when it is available.
